export const DISCORD_MODULE_OPTIONS = "DISCORD_MODULE_OPTIONS";

export const ON_MESSAGE_DECORATOR = "ON_MESSAGE_DECORATOR";
export const ON_DECORATOR = "ON_DECORATOR";
export const ONCE_DECORATOR = "ONCE_DECORATOR";

export const MIDDLEWARE_DECORATOR = "MIDDLEWARE_DECORATOR";
