export const DISCORD_MODULE_OPTIONS = 'DISCORD_MODULE_OPTIONS';

export const ON_MESSAGE_DECORATOR = 'ON_MESSAGE_DECORATOR';
export const ON_DECORATOR = 'ON_DECORATOR';
export const ONCE_DECORATOR = 'ONCE_DECORATOR';

export const MIDDLEWARE_DECORATOR = 'MIDDLEWARE_DECORATOR';
export const USE_INTERCEPTORS_DECORATOR = 'USE_INTERCEPTORS_DECORATOR';
export const USE_GUARDS_DECORATOR = 'USE_GUARDS_DECORATOR';

export const CLIENT_DECORATOR = 'CLIENT_DECORATOR';
export const ARG_NUM_DECORATOR = 'ARG_NUM_DECORATOR';

export const CONTENT_DECORATOR = 'CONTENT_DECORATOR';
export const CONTEXT_DECORATOR = 'CONTEXT_DECORATOR';
