export enum DecoratorConstant {
  ON_COMMAND_DECORATOR = 'ON_COMMAND_DECORATOR',
  ON_DECORATOR = 'ON_DECORATOR',
  ONCE_DECORATOR = 'ONCE_DECORATOR',
  MIDDLEWARE_DECORATOR = 'MIDDLEWARE_DECORATOR',
  USE_PIPES_DECORATOR = 'USE_PIPES_DECORATOR',
  USE_GUARDS_DECORATOR = 'USE_GUARDS_DECORATOR',
  CLIENT_DECORATOR = 'CLIENT_DECORATOR',
  ARG_NUM_DECORATOR = 'ARG_NUM_DECORATOR',
  ARG_RANGE_DECORATOR = 'ARG_RANGE_DECORATOR',
  CONTENT_DECORATOR = 'CONTENT_DECORATOR',
  CONTEXT_DECORATOR = 'CONTEXT_DECORATOR'
}